package work_leave

import (
	"backend/internal/domain/common"
	"time"

	"github.com/google/uuid"
)

type WorkLeaveModel struct {
	ID uuid.UUID `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id"`

	CompanyID      uuid.UUID `gorm:"type:uuid;not null;index" json:"company_id"`
	EmployeeID     uuid.UUID `gorm:"type:uuid;not null;index" json:"employee_id"`
	LeaveBalanceID uuid.UUID `gorm:"type:uuid;not null;index" json:"leave_balance_id"`

	Type      string    `gorm:"type:varchar(255);not null" json:"type"`
	Reason    string    `gorm:"type:varchar(255);not null" json:"reason"`
	StartDate time.Time `gorm:"type:date;not null" json:"start_date"`
	EndDate   time.Time `gorm:"type:date;not null" json:"end_date"`
	TotalDay  int       `gorm:"type:int;not null" json:"total_day"`

	Status          string     `gorm:"type:varchar(50);not null;index" json:"status"` // pending, approved, rejected, cancelled
	ApprovedBy      *uuid.UUID `gorm:"type:uuid" json:"approved_by"`
	ReasonRejection string     `gorm:"type:varchar(255)" json:"reason_rejection"`

	IsAutoGenerated bool   `gorm:"default:false" json:"is_auto_generated"`
	Files           string `gorm:"type:varchar(255)" json:"files,omitempty"`

	common.BaseModel
}
